### ISSUE TITLE
Not Connected Error

### ISSUE THREAD

**Issue by wheech** [AlexaCRM/integration-dynamics#4] opened 2016-10-18 11:19 UTC
Hi...
When I try to connect I get the following error:
Could not find definition of Service <OrganizationService> in provided WSDL
I have tried everything I can think of... Any ideas please...
Thanks

**Comment by wizardist** [comment] 2016-10-18 11:31
Hi @wheech 

What kind of CRM are you trying to use? Is it an On-Premises instance or Dynamics CRM Online (365)?

**Comment by wheech** [comment] 2016-10-18 11:46
Hi... thanks for picking this up... it is an on-premise installation.
I have IFD all setup and have been happily working with Outlook CRM integration for a year etc. I have also got php CURL connection working from a php website... but looking to migrate to wordpress and was hoping that this plugin would work...

**Comment by wizardist** [comment] 2016-10-18 11:50
Okay. I faced this issue earlier with IFD. I'm 95% sure it has to do with buggy WSDL importing routine in the upstream [PHP CRM Toolkit](https://github.com/AlexaCRM/php-crm-toolkit). I'll try to fix it and get back to you. Stay tuned.

**Comment by wheech** [comment] 2016-10-18 11:52
Thanks!

**Comment by wizardist** [comment] 2016-10-18 12:18
@wheech could you help me test the fix? I would need you to replace one file in the plugin, it's called `libraries/php-crm-toolkit/src/Client.php`. The file to replace with is at [Gist](adcaad7d9fb02d7a47a0a7ff886e34e1). Just download the raw version and replace the original file. Back up the original copy first! Thank you.

If it fixes the issue, then the fix will emerge in the very next plugin update.

**Comment by wheech** [comment] 2016-10-18 14:14
Hi... I have taken the Client.php in the RAW form from the https://raw.githubusercontent.com/AlexaCRM/php-crm-toolkit/ location as this is the one that seemed to be recently updated by yourself and tagged to fix this error. Unfortunately I get the same error. Could not find definition of Service <OrganizationService> in provided WSDL

**Comment by wizardist** [comment] 2016-10-18 14:28
@wheech This is quite odd - we need to go deeper.

Please provide a link to the OrganizationService, or the WSDL itself. This [MSDN help page](https://msdn.microsoft.com/en-us/library/gg309401.aspx) talks about how to perform it.

You can either share it here, or send it to my GitHub email (see in the profile) privately.

**Comment by wheech** [comment] 2016-10-18 14:35
I have responded via email. 
Thanks,

**Comment by wizardist** [comment] 2016-10-18 15:11
This issue arises due to a self-signed certificate used by the OrganizationService endpoint.

**Comment by wizardist** [comment] 2016-10-18 15:16
@wheech version 1.1.18 that fixes this issue should hit the shelves soon. Please tell whether the issue is fixed after you get the update. Thanks!

**Comment by wheech** [comment] 2016-10-18 15:35
Ok... It may take a bit of time to replace the self signed certificate. Many thanks!

**Comment by wheech** [comment] 2016-10-18 16:11
I updated and still the same I am sorry...
Do I need to manually refresh the instance or anything? I have checked that
the repo was updated.


Charlie
wheech@ntlworld.com
Mob: +44 (0)7811 127378

Beachside Holiday House for rent: www.sussexbeachhouse.co.uk

**Comment by wizardist** [comment] 2016-10-18 17:07
@wheech nope, updating the plugin should have done the trick. It's sad to hear that it didn't work. I would recommend using a certificate from a trusted authority in the meanwhile (well, not in the meanwhile but at all times). But the issue will be addressed anyway.

You can try issuing a free SSL certificate, there are multiple options in the market.

**Comment by wizardist** [comment] 2016-10-19 09:51
Hi @wheech 

A control was added in version 1.1.19 that allows ignoring invalid certificate errors. The code was fixed once again to address this issue. Please try again after you update the plugin.

![ignore_ssl_errors](https://cloud.githubusercontent.com/assets/532481/19514034/c660f56a-95fa-11e6-9b14-d0ee0ca47f8c.png)

**Comment by wheech** [comment] 2016-10-19 16:31
Thanks Pavel,

This works and it now says connected.

thanks for all your help!


Charlie
wheech@ntlworld.com
Mob: +44 (0)7811 127378

Beachside Holiday House for rent: www.sussexbeachhouse.co.uk

**Closed** 2016-10-19 16:34 UTC
Labels: bug, fixed
